define chr_warn = "{color=#b61c1c}{b}[ХАР]: {/b}{/color}"
define str_warn = "{color=#b61c1c}{b}[СИЛ]: {/b}{/color}"
define dex_warn = "{color=#b61c1c}{b}[ЛОВ]: {/b}{/color}"
define int_warn = "{color=#b61c1c}{b}[ИНТ]: {/b}{/color}"
define chr_pass = "{color=#00ff00}{b}[ХАР]: {/b}{/color}"
define str_pass = "{color=#00ff00}{b}[СИЛ]: {/b}{/color}"
define dex_pass = "{color=#00ff00}{b}[ЛОВ]: {/b}{/color}"
define int_pass = "{color=#00ff00}{b}[ИНТ]: {/b}{/color}"
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
